# insipation: https://community.home-assistant.io/t/snmp-bandwidth-monitor/7122
- alias: "Monitor Inbound Internet Traffic"
  trigger:
    platform: state
    entity_id: sensor.arris_dg2470a_router_kib_s_received
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.wan_traffic_delta_in
        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

#- alias: "Monitor Outbound Internet Traffic"
#  trigger:
#    platform: state
#    entity_id: sensor.snmp_wan_out
#  action:
#    - service: input_number.set_value
#      data:
#        entity_id: input_number.wan_traffic_delta_out
#        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'
