# Home Assistant Configuration - Uriel Zajaczkovski 
# 2020-Dec-03: Initial setup
# 2021-Jan-26: Switch to YAML mode (lovelace GUI is a mess and lacks functionality)

default_config:

# YAML mode. Raw editor in lovelace UI is disabled
lovelace:
  mode: yaml
  resources:
  # Mini Graph Card (HACS): https://github.com/kalkih/mini-graph-card
    - {type: module, url: /local/community/mini-graph-card/mini-graph-card-bundle.js?v=0.10.0}
  # Atomic Calendar Revive (HACS): https://github.com/marksie1988/atomic-calendar-revive
    - {type: module, url: /local/community/atomic-calendar-revive/atomic-calendar-revive.js}
  # Check Button Card (HACS) - https://github.com/custom-cards/check-button-card
    - {type: module, url: '/local/community/check-button-card/check-button-card.js'}
  # Scheduler Component (HACS) - https://github.com/nielsfaber/scheduler-component
    - {type: module, url: '/local/community/scheduler-card/scheduler-card.js'}
  # layout-card (HACS) - https://github.com/thomasloven/lovelace-layout-card
    - {type: module, url: '/local/community/lovelace-layout-card/layout-card.js'}
  # template-entity-row (HACS) - https://github.com/thomasloven/lovelace-template-entity-row
    - {type: module, url: '/local/community/lovelace-template-entity-row/template-entity-row.js'}
  # card-mod (HACS) - https://github.com/thomasloven/lovelace-card-mod
    - {type: module, url: '/local/community/lovelace-card-mod/card-mod.js'}

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
utility_meter: !include utility_meters.yaml

# influxDB database: https://www.home-assistant.io/integrations/influxdb/
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Bandwidth perfomance: https://www.home-assistant.io/integrations/speedtestdotnet/ 
speedtestdotnet:
  scan_interval:
    days: 0
    hours: 12
    minutes: 0
    seconds: 0
    milliseconds: 0

# Google Calendar: https://www.home-assistant.io/integrations/calendar.google
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Climate Integration: https://www.home-assistant.io/integrations/climate/
climate:
  - platform: fujitsu_general_heatpump
    username: !secret climate_username
    password: !secret climate_password 
    tokenpath: 'token.txt'

# Environment Canada: https://www.home-assistant.io/integrations/environment_canada/
weather:
  - platform: environment_canada 

camera:
  - platform: environment_canada
  - platform: generic
    name: Halifax_tides_curve
    still_image_url: https://127.0.0.1:8123/local/halifax_tides.png
    verify_ssl: false

sonoff:
  username: !secret sonoff_powr2_username
  password: !secret sonoff_powr2_password
  force_update: [temperature, power]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: [temperature, humidity, power, current, voltage]
  
input_number:
 wan_traffic_delta_in:
   min: 0
   max: 4294967295
 wan_traffic_delta_out:
   min: 0
   max: 4294967295