- platform: template
  switches:
    update_speedtest:
      value_template: "{{ is_state('switch.update_speedtest', 'on') }}"
      friendly_name: Update Speedtest
      turn_on:
      - service: switch.turn_on
        entity_id: switch.update_speedtest
        
      turn_off:
        service: switch.turn_off
        entity_id: switch.update_speedtest
